<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Module\Locations\LocationsModule $module
 * @var \Doctrine\Common\Collections\Collection $items
 * @var \Sitegear\Module\Locations\Model\Item $item
 */
$module = $view['module'];
$items = $view['items'];
$excerptDecorator = sprintf('excerpt(%d, "%s")', $view['excerpt-length'], 'Region description not found.');
if ($items->count() === 0) {
	echo $view->locations()->item(sprintf('partials/%s', $view['no-items'] ?: 'no-items'));
} else {
?>
<section class="locations-items-container">
    <h2>Locations</h2>
<?php
	foreach ($items as $item) {
		$linkUrl = $module->getRouteUrl('item', $item->getUrlPath());
		$viewScript = $module->getContentPath('item', $item->getUrlPath());
?>
	<section>
		<h3><?php echo $item->getName(); ?></h3>
		<p>
<?php echo $view->locations($excerptDecorator)->item($viewScript); ?>
		</p>
<?php
		if (isset($view['read-more'])) {
?>
		<p class="read-more"><a href="<?php echo $linkUrl ?>"><?php echo $view['read-more']; ?></a></p>
<?php
		}
?>
	</section>
<?php
	}
?>
</section>
<?php
}
?>
