<?php
/**
 * @var \Sitegear\View\View $view
 * @var \Sitegear\Module\Locations\LocationsModule $module
 * @var \Sitegear\Module\Locations\Model\Item $item
 * @var \Sitegear\Module\Locations\Model\Item $sibling
 */
$module = $view['module'];
$item = $view['item'];
$linkUrl = $module->getRouteUrl('region', $item->getRegion()->getUrlPath());
?>
<section id="locations-nearby-container">
	<h2>Nearby Locations</h2>
	<p>See other locations in <a href="<?php echo $linkUrl; ?>"><?php echo $item->getRegion()->getName(); ?></a>.</p>
<?php
$siblings = $item->getRegion()->getItems();
if ($siblings->count() > 1) { // 1 is always going to be this `$item`
?>
	<ul>
<?php
	foreach ($siblings as $sibling) {
		if ($sibling !== $item) {
			$siblingLinkUrl = $module->getRouteUrl('region', $sibling->getUrlPath());
?>
		<li><a href="<?php echo $siblingLinkUrl; ?>"><?php echo $sibling->getName(); ?></a></li>
<?php
		}
	}
?>
	</ul>
<?php
}
?>
</section>
