<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Module\Locations\Model\Region $region
 */
$view->getStringsManager()->prepend('title', $view['title']);
$regionDecorator = sprintf('excerpt(%d, "%s")', $view['excerpt-length'], 'Region description not found.');
echo sprintf('<h1>%s</h1>', $view['heading']), PHP_EOL;
if ($view['show-search'] === 'before') {
	echo $view->locations('element(section, class="locations-search-form-container")')->searchForm();
}
echo $view->locations()->item('partials/regions');
if ($view['show-search'] === 'after') {
	echo $view->locations('element(section, class="locations-search-form-container")')->searchForm();
}
