<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Base\Form\FormInterface $form
 * @var \Sitegear\Base\Form\Renderer\Factory\FormRendererFactoryInterface $rendererFactory
 */
$form = $view['form'];
$rendererFactory = $view['renderer-factory'];
$options = array(); // TODO Options??
echo implode(PHP_EOL, $rendererFactory->getElementRenderer($form->getStep($view['current-step'])->getRootElement())->render($options)), PHP_EOL;
