<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Form\FormInterface $form
 */
$form = $view['form'];
$currentStep = $view['current-step'];
$availableSteps = $view['available-steps'];
$linkStepFormat = sprintf('<a href="%%s"%s>%%s</a>', \Sitegear\Util\HtmlUtilities::attributes($view['steps']['link']['attributes'] ?: array()));
$nonLinkStepFormat = sprintf('<%s%s>%%s</%s>', $view['steps']['non-link']['element'], \Sitegear\Util\HtmlUtilities::attributes($view['steps']['non-link']['attributes'] ?: array()), $view['steps']['non-link']['element']);
$jumpUrlFormat = $view['jump-url-format'];
echo sprintf('<%s%s>', $view['outer-container']['element'], \Sitegear\Util\HtmlUtilities::attributes($view['outer-container']['attributes'] ?: array())), PHP_EOL;
for ($step=0, $count=$form->getStepsCount(); $step<$count; $step++) {
	$stepType = $step < $currentStep ? 'earlier' : ($step > $currentStep ? 'later' : 'current');
	$label = \Sitegear\Util\TokenUtilities::replaceTokens($view['steps'][$stepType]['label-format'], array( 'heading' => $form->getStep($step)->getHeading() ));
	$containerAttributes = array_merge(
		$view['item-container']['attributes'] ?: array(),
		$view['steps'][$stepType]['container-attributes'] ?: array()
	);
	echo "\t" . sprintf('<%s%s>', $view['item-container']['element'], \Sitegear\Util\HtmlUtilities::attributes($containerAttributes)), PHP_EOL;
	echo "\t\t";
	if (in_array($step, $availableSteps) && $step !== $currentStep) {
		echo sprintf($linkStepFormat, sprintf($jumpUrlFormat, $step), $label), PHP_EOL;
	} else {
		echo sprintf($nonLinkStepFormat, $label), PHP_EOL;
	}
	echo "\t" . sprintf('</%s>', $view['item-container']['element']), PHP_EOL;
}
echo sprintf('</%s>', $view['outer-container']['element']), PHP_EOL;
