<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Core\Module\Locations\LocationsModule $module
 * @var \Sitegear\Core\Module\Locations\Model\Region $region
 * @var \Sitegear\Core\Module\Locations\Model\Region $subRegion
 * @var \Sitegear\Core\Module\Locations\Model\Item $item
 */
$module = $view['module'];
$region = $view['region'];
$view->getStringsManager()->prepend('title', $view['title']);
$view->getStringsManager()->prepend('title', $region->getName());
echo sprintf('<h1>%s</h1>', $region->getName()), PHP_EOL;
echo $view->locations('editable')->item($module->getContentPath('region', $region->getUrlPath()));
echo $view->locations()->item('partials/map');
echo $view->locations()->item('partials/items');
echo $view->locations()->item('partials/regions');
