<?php
/** @var \Sitegear\Core\View\View $view */
$field = $view['field'];
$attributes = array_merge(
	array(
		'type' => 'text'
	),
	isset($field['attributes']) ? $field['attributes'] : array(),
	array(
		'name' => $view['name'],
		'value' => $view['value']
	)
);
if (!isset($attributes['id'])) {
	$attributes['id'] = sprintf('%s%s', $view['form-id-prefix'], $view['name']);
}
echo sprintf('<span id="%s" class="ui-helper-clearfix">', $attributes['id']), PHP_EOL;
echo sprintf('<input type="hidden" name="%s" value="" />', $view['name']), PHP_EOL;
foreach ($field['values'] as $valueIndex => $valueSpec) {
	$elementAttributes = array_merge(
		$attributes,
		array(
			'id' => sprintf('%s-checkbox-%s', $attributes['id'], $valueIndex),
			'type' => 'checkbox', // TODO Allow radio buttons
			'value' => $valueSpec['value']
		)
	);
	// TODO move class names into config - 'checkbox' and 'checkbox-label' (below)
	if (!isset($elementAttributes['class'])) {
		$elementAttributes['class'] = 'checkbox';
	} else {
		$elementAttributes['class'] .= ' checkbox';
	}
	if ($valueSpec['value'] === $view['value']) {
		$elementAttributes['checked'] = 'checked';
	}
	echo sprintf('<input%s /><label class="checkbox-label" for="%s">%s</label> ', \Sitegear\Util\HtmlUtilities::attributes($elementAttributes), $elementAttributes['id'], $valueSpec['label']), PHP_EOL;
}
echo '</span>', PHP_EOL;
