<?php
/** @var \Sitegear\Core\View\View $view */
$field = $view['field'];
$attributes = array_merge(
	$field['attributes'],
	array(
		'name' => $field['name'],
		'value' => $view['value']
	)
);
if (!isset($attributes['id'])) {
	$attributes['id'] = sprintf('%s%s', $view['form-id-prefix'], $view['name']);
}
echo sprintf('<select%s>', \Sitegear\Util\HtmlUtilities::attributes($attributes)), PHP_EOL;
foreach ($field['values'] as $value => $label) {
	$labelText = is_array($label) ? $label['label'] : $label;
	$attributes = (is_array($label) && isset($label['attributes'])) ? $label['attributes'] : array();
	$attributes['value'] = $value;
	echo sprintf('<option%s>%s</option>', \Sitegear\Util\HtmlUtilities::attributes($attributes), $labelText);
}
echo '</select>', PHP_EOL;
