<?php
/** @var \Sitegear\Core\View\View $view */
$field = $view['field'];
$attributes = array_merge(
	isset($field['attributes']) ? $field['attributes'] : array(),
	array(
		'name' => $view['name']
	)
);
if (!isset($attributes['id'])) {
	$attributes['id'] = sprintf('%s%s', $view['form-id-prefix'], $view['name']);
}
echo sprintf('<select%s>', \Sitegear\Util\HtmlUtilities::attributes($attributes)), PHP_EOL;
foreach ($field['options'] as $option) {
	$labelText = $option['label'];
	$attributes = isset($option['attributes']) ? $option['attributes'] : array();
	$attributes['value'] = $option['value'];
	if ($option['value'] === $view['value']) {
		$attributes['selected'] = 'selected';
	}
	echo sprintf('<option%s>%s</option>', \Sitegear\Util\HtmlUtilities::attributes($attributes), $labelText);
}
echo '</select>', PHP_EOL;
