<?php
/** @var \Sitegear\Core\View\View $view */
$field = $view['field'];
$attributes = array_merge(
	isset($field['attributes']) ? $field['attributes'] : array(),
	array(
		'name' => $view['name']
	)
);
if (!isset($attributes['id'])) {
	$attributes['id'] = sprintf('%s%s', $view['form-id-prefix'], $view['name']);
}
echo sprintf('<textarea%s>%s</textarea>', \Sitegear\Util\HtmlUtilities::attributes($attributes), $view['value']), PHP_EOL;
