<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Module\Customer\Model\TransactionItem $item
 */
?>
<table class="<?php echo $view['table-classes']['table']; ?>">
	<thead>
	<tr>
		<th class="<?php echo $view['table-classes']['columns']['item']; ?>">
			<?php echo $view['text']['table-headings']['item']; ?>
		</th>
		<th class="<?php echo $view['table-classes']['columns']['price']; ?>">
			<?php echo $view['text']['table-headings']['price']; ?>
		</th>
		<th class="<?php echo $view['table-classes']['columns']['quantity']; ?>">
			<?php echo $view['text']['table-headings']['quantity']; ?>
		</th>
		<th class="<?php echo $view['table-classes']['columns']['total']; ?>">
			<?php echo $view['text']['table-headings']['total']; ?>
		</th>
		<th class="<?php echo $view['table-classes']['columns']['actions']; ?>">
			<?php echo $view['text']['table-headings']['actions']; ?>
		</th>
	</tr>
	</thead>
	<tbody>
<?php
$totalPrice = 0;
foreach ($view['trolley-data'] as $index => $item) {
	$totalPrice += $item->getQuantity() * $item->getUnitPrice();
	$inputId = sprintf('item-%d-quantity', $index);
?>
	<tr class="<?php echo $view['table-classes']['rows']['item']; ?>">
		<td class="<?php echo $view['table-classes']['columns']['item']; ?>">
			<div class="<?php echo $view['table-classes']['extra']['item-label-container']; ?>">
				<a href="<?php echo $item->getDetailsUrl(); ?>"><?php echo $item->getLabel(); ?></a>
			</div>
			<div class="<?php echo $view['table-classes']['extra']['item-attributes-container']; ?>">
				<?php echo implode('<br/>', array_map(function($attribute) { return $attribute['label']; }, $item->getAttributes())); ?>
			</div>
		</td>
		<td class="<?php echo $view['table-classes']['columns']['price']; ?>">
			$<?php echo number_format($item->getUnitPrice() / 100, 2); ?>
		</td>
		<td class="<?php echo $view['table-classes']['columns']['quantity']; ?>">
			<form method="post" action="<?php echo $view['modify-item-url']; ?>" class="<?php echo $view['table-classes']['forms']['modify']; ?>">
				<nobr>
					<input type="hidden" name="form-url" value="<?php echo $view['form-url']; ?>" />
					<input type="hidden" name="index" value="<?php echo $index; ?>" />
					<label for="<?php echo $inputId; ?>" style="display:none;"></label>
					<input type="text" name="quantity" id="<?php echo $inputId; ?>" value="<?php echo number_format($item->getQuantity()); ?>" style="width:2em;" />
					<input type="submit" value="<?php echo $view['text']['quantity-button']; ?>" />
				</nobr>
			</form>
		</td>
		<td class="<?php echo $view['table-classes']['columns']['total']; ?>">
			$<?php echo number_format($item->getUnitPrice() * $item->getQuantity() / 100, 2); ?>
		</td>
		<td class="<?php echo $view['table-classes']['columns']['actions']; ?>">
			<form method="post" action="<?php echo $view['remove-item-url']; ?>" class="<?php echo $view['table-classes']['forms']['remove']; ?>">
				<input type="hidden" name="form-url" value="<?php echo $view['form-url']; ?>" />
				<input type="hidden" name="index" value="<?php echo $index; ?>" />
				<input type="submit" value="<?php echo $view['text']['remove-button']; ?>" />
			</form>
		</td>
	</tr>
<?php
}
?>
	<tr class="<?php echo $view['table-classes']['rows']['subtotal']; ?>">
		<td colspan="3" class="<?php echo $view['table-classes']['columns']['total-label']; ?>">
			<?php echo $view['text']['table-total-labels']['subtotal']; ?>
		</td>
		<td class="<?php echo $view['table-classes']['columns']['total']; ?>">
			$<?php echo number_format($totalPrice / 100, 2); ?>
		</td>
		<td  class="<?php echo $view['table-classes']['columns']['checkout-link-container']; ?>" rowspan="<?php echo 2 + sizeof($view['adjustments']); ?>">
			<?php /** TODO Allow this to be hidden */ ?>
			<?php echo \Sitegear\Util\TokenUtilities::replaceTokens($view['text']['checkout-link'], array( 'checkoutUrl' => $view['checkout-url'] )); ?>
		</td>
	</tr>
<?php
foreach ($view['adjustments'] as $adjustment) {
?>
	<tr class="<?php echo $view['table-classes']['rows']['adjustment']; ?>">
		<td colspan="3" class="<?php echo $view['table-classes']['columns']['total-label']; ?>">
			<?php echo $adjustment['label']; ?>
		</td>
		<td class="<?php echo $view['table-classes']['columns']['total']; ?>">
			<?php echo is_null($adjustment['value']) ? $view['text']['unknown-value'] : '$' . number_format($adjustment['value'] / 100, 2); ?>
		</td>
	</tr>
<?php
}
?>
	<tr class="<?php echo $view['table-classes']['rows']['total']; ?>">
		<td colspan="3" class="<?php echo $view['table-classes']['columns']['total-label']; ?>">
			<?php echo $view['text']['table-total-labels']['total']; ?>
		</td>
		<td class="<?php echo $view['table-classes']['columns']['total']; ?>">
			<?php echo $view['text']['unknown-value']; ?>
		</td>
	</tr>
	</tbody>
</table>
