<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Ext\Module\Locations\Model\Item $item
 * @var \Sitegear\Ext\Module\Locations\Model\Item $sibling
 */
$item = $view['item'];
$linkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['region-url'], $item->getRegion()->getUrlPath());
?>
<section id="locations-nearby-container">
	<h2>Nearby Locations</h2>
	<p>See other locations in <a href="<?php echo $linkUrl; ?>"><?php echo $item->getRegion()->getName(); ?></a>.</p>
<?php
$siblings = $item->getRegion()->getItems();
if ($siblings->count() > 1) { // 1 is always going to be this `$item`
?>
	<ul>
<?php
	foreach ($siblings as $sibling) {
		if ($sibling !== $item) {
			$siblingLinkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['item-url'], $sibling->getUrlPath())
?>
		<li><a href="<?php echo $siblingLinkUrl; ?>"><?php echo $sibling->getName(); ?></a></li>
<?php
		}
	}
?>
	</ul>
<?php
}
?>
</section>
