<?php
/**
 * @var \Sitegear\Core\View\View $view
 */
$trolleyEmpty = !isset($view['trolley-data']) || empty($view['trolley-data']);
if ($trolleyEmpty) {
	echo $view['text']['no-items'];
} else {
	echo \Sitegear\Util\TokenUtilities::replaceTokens(
		$view['text']['items-count'][sizeof($view['trolley-data']) === 1 ? 0 : 1],
		array(
			'count' => sizeof($view['trolley-data'])
		)
	);
}
$showDetailsLink = is_bool($view['links']['details']) ? $view['links']['details'] : ($view['links']['details'] === 'non-empty' && !$trolleyEmpty);
$showCheckoutLink = is_bool($view['links']['checkout']) ? $view['links']['checkout'] : ($view['links']['checkout'] === 'non-empty' && !$trolleyEmpty);
if ($showDetailsLink || $showCheckoutLink) {
	$linkWrapper = $view['links']['wrapper']['element'];
	if (is_string($linkWrapper)) {
		echo sprintf('<%s%s>', $linkWrapper, \Sitegear\Util\HtmlUtilities::attributes($view['links']['wrapper']['attributes']));
	}
	if ($showDetailsLink) {
		echo \Sitegear\Util\TokenUtilities::replaceTokens(
			$view['text']['details-link'],
			array(
				'detailsUrl' => $view['details-url']
			)
		);
	}
	echo $view['links']['separator'];
	if ($showCheckoutLink) {
		echo \Sitegear\Util\TokenUtilities::replaceTokens(
			$view['text']['checkout-link'],
			array(
				'checkoutUrl' => $view['checkout-url']
			)
		);
	}
	if (is_string($linkWrapper)) {
		echo sprintf('</%s>', $linkWrapper);
	}
}
