<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Core\Module\News\NewsModule $module
 * @var \Sitegear\Core\Module\News\Model\Item $item
 */
$module = $view['module'];
$item = $view['item'];
$view->getStringsManager()->prepend('title', $view['title'])->prepend('title', $item->getHeadline());
$published = \Sitegear\Util\TokenUtilities::replaceTokens(
	$view['published'],
	array(
		'publishedDate' => $item->getDatePublished()->format($view['date-format'])
	)
);
$backLink = \Sitegear\Util\TokenUtilities::replaceTokens(
	$view['back-link'],
	array(
		'indexUrl' => $module->getRouteUrl('index')
	)
);
?>
<h1><?php echo $item->getHeadline() ?></h1>
<?php echo $view->news()->item('items/' . $item->getUrlPath()); ?>
<p><?php echo $published; ?></p>
<p><?php echo $backLink; ?></p>
