<?php
/**
 * @var \Sitegear\View\View $view
 */
$view->getStringsManager()->prepend('Login as Guest', 'title');
?>
<h1>Login as Guest</h1>
<p>
Please enter below to login as guest.
Any personal information you enter will not be stored and therefore will not be available for future visits.
</p>
<?php echo $view->userIntegration()->selector(); ?>
<?php echo $view->forms()->form($view['form-key']); ?>
