<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Ext\Module\Products\ProductsModule $module
 * @var \Sitegear\Ext\Module\Products\Model\Category $category
 */
$module = $view['module'];
$view->getStringsManager()->prepend('title', $view['title']);
$categoryDecorator = sprintf('excerpt(%d, "%s")', $view['excerpt-length'], 'Category description not found.');
?>
<h1><?php echo $view['heading']; ?></h1>

<section class="products-categories-container">
<?php
if (empty($view['categories'])) {
	echo $view->products()->noCategories();
} else {
?>
	<h2>Categories</h2>
<?php
	foreach ($view['categories'] as $category) {
		$linkUrl = $module->getRouteUrl('category', $category->getUrlPath());
		$viewScript = sprintf('%s/%s', $view['category-path'], $category->getUrlPath());
?>
	<section>
		<h3><?php echo $category->getName(); ?></h3>
		<p>
<?php echo $view->products($categoryDecorator)->item($viewScript); ?>
		</p>
<?php
		if (isset($view['read-more'])) {
?>
		<p class="read-more"><a href="<?php echo $linkUrl ?>"><?php echo $view['read-more']; ?></a></p>
<?php
		}
?>
	</section>
<?php
	}
}
?>
</section>
