<?php
// TODO Editable product name and specifications
// TODO Add to trolley form (integration with Base\Customer module)
/** @var \Sitegear\Core\View\View $view */
/** @var \Sitegear\Ext\Module\Products\Model\Item $item  */
$item = $view['item'];
$view->getStringsManager()->prepend('title', $view['title'])->prepend('title', $item->getName());
?>
<h1><?php echo $item->getName(); ?></h1>
<?php
// ITEM DESCRIPTION
echo $view->products('editable')->item(sprintf('%s/%s', $view['item-path'], $item->getUrlPath()));

// PURCHASE FORM
if ($view['display-add-to-trolley-form']) {
	echo $view->customer()->trolleyForm('products', 'item', $item->getId());
}

// ITEM SPECIFICATIONS
if (sizeof($item->getSpecifications()) > 0) {
?>
<div class="product-specifications">
	<h2>Specifications</h2>
	<table>
<?php
	$odd = true;
	foreach ($item->getSpecifications() as $specification) { /** @var \Sitegear\Ext\Module\Products\Model\Specification $specification */
?>
		<tr class="<?php echo $odd ? 'odd' : 'even'; ?>">
			<td class="label">
				<?php echo $specification->getLabel(); ?>
			</td>
			<td class="value">
				<?php echo $specification->getValue(); ?>
			</td>
		</tr>
<?php
		$odd = !$odd;
	}
?>
	</table>
</div>
<?php
}

// RELATED ITEMS
if (sizeof($item->getRelationships()) > 0) {
?>
<div class="product-relationships">
	<h2>Related Items</h2>
	<ul>
<?php
	foreach ($item->getRelationships() as $relationship) { /** @var \Sitegear\Ext\Module\Products\Model\Relationship $relationship */
		$linkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['item-url'], $relationship->getRelatedItem()->getUrlPath());
?>
		<li><a href="<?php echo $linkUrl; ?>"><?php echo $relationship->getRelatedItem()->getName(); ?></a></li>
<?php
	}
?>
	</ul>
</div>
<?php
}

// CATEGORY ASSIGNMENTS
if (sizeof($item->getCategoryAssignments()) > 0) {
?>
<div class="product-category-assignments">
	<h2>Related Categories</h2>
	<ul>
<?php
	foreach ($item->getCategoryAssignments() as $categoryAssignment) { /** @var \Sitegear\Ext\Module\Products\Model\CategoryAssignment $categoryAssignment */
		$linkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['category-url'], $categoryAssignment->getCategory()->getUrlPath());
?>
		<li><a href="<?php echo $linkUrl; ?>"><?php echo $categoryAssignment->getCategory()->getName(); ?></a></li>
<?php
	}
?>
	</ul>
</div>
<?php
}
