<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Module\Customer\Model\Account $account
 * @var \Sitegear\Module\Customer\Model\Transaction $transaction
 * @var \Sitegear\Module\Customer\Model\TransactionItem $item
 * @var \Sitegear\Module\Customer\Model\Field $field
 * @var \Sitegear\Module\Customer\Model\AccountFieldValue $accountFieldValue
 */
$account = $view['account'];
$view->getStringsManager()->prepend('title', $view['title']);
?>
<h1><?php echo $view['heading']; ?></h1>
<p>
You are logged in as <strong><?php echo $account->getEmail() ?></strong>.
</p>
<h2>Your Details</h2>
<?php
if ($account->getFieldValues()->count() === 0) {
?>
<p>
You do not yet have any stored details.
</p>
<?php
} else {
?>
<p>
Here are your details according to your most recent transaction or update.
</p>
<table>
	<tbody>
<?php
	foreach ($view['fields'] as $field) {
		foreach ($account->getFieldValues() as $accountFieldValue) {
			if ($accountFieldValue->getField()->getId() === $field->getId()) {
?>
	<tr>
		<td class="label"><?php echo $field->getLabel(); ?></td>
		<td class="value"><?php echo $accountFieldValue->getValue() ?: '<i>{empty}</i>'; ?></td>
	</tr>
<?php
			}
		}
	}
?>
	</tbody>
</table>
<?php
}

if ($view['transaction-count'] > 0) {
	$transactionCount = min($view['transaction-count'], $account->getTransactions()->count());
?>
<h2>Your Recent Transactions</h2>
<?php
	if ($transactionCount === 0) {
?>
<p>
You do not yet have any transactions.
</p>
<?php
	} else {
?>
<p>
Here are your most recent <?php echo $transactionCount; ?> transactions.
</p>
<table>
	<thead>
	<tr>
		<th>Transaction Date</th>
		<th>Items Purchased</th>
		<th>Total Price</th>
	</tr>
	</thead>
	<tbody>
<?php
		foreach (array_slice($account->getTransactions()->toArray(), 0, $transactionCount) as $transaction) {
			$totalPrice = 0;
			foreach ($transaction->getItems() as $item) {
				$totalPrice += $item->getUnitPrice() * $item->getQuantity();
			}
?>
	<tr>
		<td><?php echo $transaction->getDatePurchased()->format($view['date-format']); ?></td>
		<td><?php echo $transaction->getItems()->count(); ?></td>
		<td><?php echo sprintf('$%s', number_format($totalPrice / 100, 2)); ?></td>
	</tr>
<?php
		}
?>
	</tbody>
</table>
<?php
	}
}
