<?php
/**
 * @var \Sitegear\View\View $view
 */
if (!empty($view['messages'])) {
	echo sprintf('<%s%s>', $view['outer-element'], \Sitegear\Util\HtmlUtilities::attributes($view['outer-attributes'])), PHP_EOL;
	foreach ($view['messages'] as $message) {
		$innerAttributes = $view['inner-attributes'];
		if (isset($message['class'])) {
			$innerAttributes = \Sitegear\Util\ArrayUtilities::mergeHtmlAttributes($innerAttributes, array( 'class' => $message['class'] ));
		}
		echo sprintf('<%s%s>%s</%s>', $view['inner-element'], \Sitegear\Util\HtmlUtilities::attributes($innerAttributes), $message['message'], $view['inner-element']), PHP_EOL;
	}
	echo sprintf('</%s>', $view['outer-element']), PHP_EOL;
}
