<?php
/** @var \Sitegear\Core\View\View $view */

// The first three fields are fixed, and they are all hidden fields.  This carries the information needed to determine
// the unit price and other details of the project, once it is submitted to the Customer Module.
$fieldDefinitions = array(
	'module' => array(
		'component' => 'input',
		'attributes' => array(
			'type' => 'hidden'
		),
		'default' => $view['module']
	),
	'type' => array(
		'component' => 'input',
		'attributes' => array(
			'type' => 'hidden'
		),
		'default' => $view['type']
	),
	'id' => array(
		'component' => 'input',
		'attributes' => array(
			'type' => 'hidden'
		),
		'default' => $view['id']
	)
);
$fields = array(
	'module',
	'type',
	'id'
);

// Every item attribute is an additional field in the form.
foreach ($view['attribute-definitions'] as $attribute) { /** @var \Sitegear\Ext\Module\Products\Model\Attribute $attribute */
	$component = 'select'; // TODO Others
	$default = ''; // TODO Default value
	// TODO Configurable text and sprintf() format mask.
	$values = array( '' => 'Please Select...' );
	foreach ($attribute['options'] as $option) {
		$values[$option['id']] = sprintf('%s - $%.2f', $option['label'], $option['value'] / 100);
	}
	$name = sprintf('attr_%s', $attribute['id']);
	$fieldDefinitions[$name] = array(
		'component' => $component,
		'label' => $attribute['label'],
		'default' => $default,
		'values' => $values,
		'validators' => array(
			array(
				'constraint' => 'not-blank'
			)
		)
	);
	$fields[] = $name;
}

// Add the quantity field, which is a standard text field with a label.
// TODO Validation
$fieldDefinitions['qty'] = array(
	'component' => 'input',
	// TODO Configurable label
	'label' => 'Quantity',
	'default' => 1
);
$fields[] = 'qty';

// Display the combined form.
$form = array(
	'action-url' => sprintf('%s/add-trolley-item', $view['root-url']),
	'submit-button' => 'Buy Now',
	'reset-button' => false,
	'fields' => $fieldDefinitions,
	'pages' => array(
		array(
			'fieldsets' => array(
				array(
					'fields' => $fields
				)
			)
		)
	)
);
echo $view->forms()->form('add-trolley-item', $form);
