<?php
/** @var \Sitegear\Core\View\View $view */
$hidden = array( 'attributes' => array( 'type' => 'hidden' ));
?>
<form name="add-trolley-item" id="add-trolley-item">
<?php
echo $view->forms()->input('module', $hidden, $view['module']);
echo $view->forms()->input('type', $hidden, $view['type']);
echo $view->forms()->input('id', $hidden, $view['id']);
?>
	<fieldset>
<?php
foreach ($view['attribute-definitions'] as $name => $attribute) {
	$component = 'select'; // TODO Others
	$default = ''; // TODO Default value
	// TODO Configurable text and sprintf() format mask.
	$values = array( '' => 'Please Select...' );
	foreach ($attribute as $label => $value) {
		$values[$value] = sprintf('%s - $%.2f', $label, $value / 100);
	}
	$fieldDefinition = array(
		'component' => $component,
		'name' => $name,
		'label' => $name,
		'default' => $default,
		'values' => $values
	);
	echo $view->forms()->fieldWrapper('add-trolley-item', array( 'field' => $name, 'mode' => 'field', 'definition' => $fieldDefinition ));
}
echo $view->forms()->fieldWrapper('add-trolley-item', array( 'field' => 'qty', 'mode' => 'field', 'definition' => array( 'component' => 'input', 'label' => 'Quantity', 'default' => '1' ) ));
?>
		<div class="buttons">
			<input type="submit" value="Buy Now" />
		</div>
	</fieldset>
</form>
