<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Ext\Module\Customer\Model\Account $account
 */
if ($view['account']) {
	$account = $view['account'];
?>
<h1>Customer Profile</h1>
<p>
You are logged in as <strong><?php echo $account->getEmail() ?></strong>.
</p>
<?php
} else {
?>
<h1>Not Logged In</h1>
<p>
You need to be <a href="<?php echo $view['login-url']; ?>">logged in</a> to view this page.
</p>
<?php
}
?>
