<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Ext\Module\Locations\Model\Item $item
 */
$item = $view['item'];
echo $view->google()->map(
	'#map',
	$item->getMapdata(),
	// TODO This is forcing the API key to be set in GoogleModule config, do we want this? Maybe it shouldn't even be a parameter here?
	null,
	array(
		array_merge(
			$item->getMapdata(),
			array(
				'name' => $item->getName()
			)
		)
	),
	true
);
