<?php
/** @var \Sitegear\Core\View\View $view */
/** @var \Sitegear\Ext\Module\Locations\Model\Region $region */
/** @var \Sitegear\Ext\Module\Locations\Model\Item $item */
$region = $view['region'];
$locations = array();
foreach ($region->getItems() as $item) {
	$locations[] = array_merge(
		$item->getMapdata(),
		array(
			'name' => $item->getName(),
			'url' => sprintf('%s/%s/%s', $view['root-url'], $view['item-url'], $item->getUrlPath())
		)
	);
}
echo $view->google()->map(
	'#map',
	$region->getMapdata(),
	// TODO This is forcing the API key to be set in GoogleModule config, do we want this? Maybe it shouldn't even be a parameter here?
	null,
	$locations,
	false
);
