<?php
/** @var \Sitegear\Core\View\View $view */
$jsonFormatter = new \Sitegear\Util\JsonFormatter();
$jsonFormatter->setInitialIndentLevel(2);
$view->getResourcesManager()->register('script:api:google', 'script', $view['apiScriptUrl'], true);
$view->getResourcesManager()->activate('script:google:maps');
?>
<script>//<![CDATA[
(function() {
	$.sitegear.initialiseGoogleMap(
		$('<?php echo $view['selector']; ?>'),
		<?php echo $jsonFormatter->formatJson($view['initialView']); ?>,
		<?php echo $jsonFormatter->formatJson($view['markers']); ?>,
		<?php echo $jsonFormatter->formatJson($view['options']); ?>,
		<?php echo $view['autoShowInfoWindow'] ? 'true' : 'false'; echo "\n"; ?>
	);
}());
//]]></script>
