<?php
/** @var \Sitegear\Core\View\View $view */
$view->getStringsManager()->prepend('title', $view['title']);
/** @var \Sitegear\Ext\Module\Products\Entities\Category $category */
$category = $view['category'];
$view->getStringsManager()->prepend('title', $category->getName());
$excerptDecorator = sprintf('excerpt(%d, "%s")', $view['excerpt-length'], 'Category description not found.');
?>
<h1><?php echo $category->getName(); ?></h1>

<?php echo $view->products('editable')->item(sprintf('%s/%s', $view['category-path'], $category->getUrlPath())); ?>

<?php
if (empty($view['items'])) {
	echo $view->products()->emptyCategory();
} else {
?>
<section class="product-items-container">
	<h2>Products</h2>
<?php
	foreach ($view['items'] as $item) { /** @var \Sitegear\Ext\Module\Products\Entities\Item $item */
		$linkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['item-url'], $item->getUrlPath());
		$viewScript = sprintf('%s/%s', $view['item-path'], $item->getUrlPath());
?>
	<section>
		<h3><?php echo $item->getName(); ?></h3>
		<p>
<?php echo $view->products($excerptDecorator)->item($viewScript); ?>
		</p>
<?php
		if (isset($view['read-more'])) {
?>
		<p class="read-more"><a href="<?php echo $linkUrl ?>"><?php echo $view['read-more']; ?></a></p>
<?php
		}
?>
	</section>
<?php
	}
?>
</section>
<?php
}
?>

<?php
if (!empty($view['categories'])) {
?>
<section class="product-categories-container">
	<h2>Subcategories</h2>
	<p>
	The <?php echo $category->getName(); ?> category contains <?php echo number_format(sizeof($view['categories'])); ?> subcategories.
	</p>
<?php
	foreach ($view['categories'] as $subcategory) { /** @var \Sitegear\Ext\Module\Products\Entities\Category $subcategory */
		$linkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['category-url'], $subcategory->getUrlPath());
		$viewScript = sprintf('%s/%s', $view['category-path'], $subcategory->getUrlPath());
?>
	<section>
		<h3><?php echo $subcategory->getName(); ?></h3>
		<p>
<?php echo $view->products($excerptDecorator)->item($viewScript); ?>
		</p>
<?php
		if (isset($view['read-more'])) {
?>
		<p class="read-more"><a href="<?php echo $linkUrl ?>"><?php echo $view['read-more']; ?></a></p>
<?php
		}
?>
	</section>
<?php
	}
?>
</section>
<?php
}
