<?php
/*!
 * This file is a part of Sitegear.
 * Copyright (c) Ben New, Leftclick.com.au
 * See the LICENSE and README files in the main source directory for details.
 * http://sitegear.org/
 */

namespace Sitegear\Base\View\Decorator;

use Sitegear\Base\View\Decorator\DecoratorInterface;
use Sitegear\Base\View\ViewInterface;

use Symfony\Component\HttpFoundation\Request;

/**
 * Decorator that replaces tokens in the received content, with content generated by a strings manager.  In this way,
 * the tokens can be written at any time (e.g. in the <head> for <title> tags) and when the token is replaced after the
 * complete rendering cycle, it will include all resources including those that are registered after the token is
 * written.
 *
 * Intended to be used at the template level only.
 */
class StringTokensDecorator implements DecoratorInterface {

	//-- DecoratorInterface Methods --------------------

	/**
	 * @inheritdoc
	 */
	public function decorate($content, ViewInterface $view=null) {
		$manager = $view->getEngine()->getViewFactory()->getStringsManager();
		foreach ($manager->getKeys() as $key) {
			$pattern = self::pattern($key);
			$content = preg_replace($pattern, $manager->render($key), $content);
		}
		return $content;
	}

	//-- Utility Methods --------------------

	/**
	 * Retrieve a token that can later be replaced by a rendering of all resources of the given type, using the
	 * pattern() method.
	 *
	 * @param string $key
	 *
	 * @return string Token, which is in the form of a HTML comment in case a problem occurs and the token is never
	 *   replaced.
	 */
	public static function token($key) {
		return sprintf('<!--[[ sitegear.strings.%s ]]-->', $key);
	}

	/**
	 * Get the regular expression that can be used to find and replace tokens generated by the token() method.
	 *
	 * @param string $key
	 *
	 * @return string Regular expression pattern, including delimiters.
	 */
	public static function pattern($key) {
		return sprintf('/<\\!\\-\\-\\[\\[\s*sitegear\\.strings\\.%s\s*\\]\\]\\-\\->/', $key);
	}

}
