<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Ext\Module\Locations\Model\Item $item
 * @var \Sitegear\Ext\Module\Locations\Model\Item $sibling
 */
// TODO Editable name etc
$item = $view['item'];
$view->getStringsManager()->prepend('title', $view['title'])->prepend('title', $item->getName());
$linkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['region-url'], $item->getRegion()->getUrlPath());
$address = array();
foreach (array('getSuburb', 'getStateOrProvince', 'getPostcode', 'getCountry') as $getter) {
	$value = $item->$getter();
	if (strlen($value) > 0) {
		$address[] = $value;
	}
}
?>
<h1><?php echo $item->getName(); ?></h1>
<?php echo $view->products('editable')->item(sprintf('%s/%s', $view['item-path'], $item->getUrlPath())); ?>

<section id="locations-address-container">
	<h2>Address</h2>
<?php
if (strlen($item->getStreetAddress()) > 0) {
?>
	<p><?php echo $item->getStreetAddress(); ?></p>
<?php
}
if (!empty($address)) {
?>
	<p><?php echo implode(', ', $address); ?></p>
<?php
}
?>
</section>

<section id="locations-map-container">
	<h2>Map</h2>
	<div id="map"></div>
</section>

<section id="locations-nearby-container">
	<h2>Nearby Locations</h2>
	<p>See other locations in <a href="<?php echo $linkUrl; ?>"><?php echo $item->getRegion()->getName(); ?></a>.</p>
<?php
$siblings = $item->getRegion()->getItems();
if ($siblings->count() > 1) { // 1 is always going to be this `$item`
?>
	<ul>
<?php
	foreach ($siblings as $sibling) {
		if ($sibling !== $item) {
			$siblingLinkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['item-url'], $sibling->getUrlPath())
?>
		<li><a href="<?php echo $siblingLinkUrl; ?>"><?php echo $sibling->getName(); ?></a></li>
<?php
		}
	}
?>
	</ul>
<?php
}
?>
</section>
