<?php
// TODO Editable name etc
/** @var \Sitegear\Core\View\View $view */
/** @var \Sitegear\Ext\Module\Locations\Model\Item $item  */
$item = $view['item'];
$view->getStringsManager()->prepend('title', $view['title'])->prepend('title', $item->getName());
?>
<h1><?php echo $item->getName(); ?></h1>
<?php
// ITEM DESCRIPTION
echo $view->products('editable')->item(sprintf('%s/%s', $view['item-path'], $item->getUrlPath()));

// REGION BACKLINK
$linkUrl = sprintf('%s/%s/%s', $view['root-url'], $view['region-url'], $item->getRegion()->getUrlPath());
?>
<p>
See other locations in <a href="<?php echo $linkUrl; ?>"><?php echo $item->getRegion()->getName(); ?></a>
</p>
