<?php
/**
 * @var \Sitegear\Core\View\View $view
 * @var \Sitegear\Ext\Module\News\Model\Item $item
 */
$item = $view['item'];
$view->getStringsManager()->prepend('title', $view['title'])->prepend('title', $item->getHeadline());
$published = \Sitegear\Util\TokenUtilities::replaceTokens(
	$view['published'],
	array(
		'publishedDate' => $item->getDatePublished()->format($view['date-format'])
	)
);
$backLink = \Sitegear\Util\TokenUtilities::replaceTokens(
	$view['back-link'],
	array(
		'indexUrl' => $view['index-url']
	)
);
?>
<h1><?php echo $item->getHeadline() ?></h1>
<?php echo $view->news()->item('items/' . $item->getUrlPath()); ?>
<p><?php echo $published; ?></p>
<p><?php echo $backLink; ?></p>
