<?php
/** @var \Sitegear\Core\View\View $view */
$field = $view['field'];
$attributes = array_merge(
	isset($field['attributes']) ? $field['attributes'] : array(),
	array(
		'name' => $view['name']
	)
);
if (!isset($attributes['id'])) {
	$attributes['id'] = sprintf('%s%s', $view['form-id-prefix'], $view['name']);
}
?>
<textarea<?php echo \Sitegear\Util\HtmlUtilities::attributes($attributes); ?>><?php echo $view['value']; ?></textarea>
